# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:
let
  go-gogs-client = buildGoPackage rec {
    name = "go-gogs-client-${version}";
    version = "20160511-${stdenv.lib.strings.substring 0 7 rev}";
    rev = "01270dfe22e92d99ce9402fedba4530ad8810100";

    goPackagePath = "github.com/gogits/go-gogs-client";

    src = fetchgit {
      inherit rev;
      url = "https://github.com/gogits/go-gogs-client";
      sha256 = "1kn3yd5nybnl69chwqjrkrvmipcg5530ny8mzsabrvpjy41nw3ka";
    };

    patches = [
      ./go-gogs-client_addCollaborator.patch
      ./go-gogs-client_addOrgMembership.patch
      ./go-gogs-client_maxRepoCreationAPI.patch
    ];
  };
in
buildGoPackage rec {
  name = "gogs-${version}";
  version = "20160612-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "26342b0c2457ba3b8a79e05be75f85258b0e82eb";

  goPackagePath = "github.com/gogits/gogs";

  src = fetchgit {
    inherit rev;
    url = "git://github.com/gogits/gogs.git";
    sha256 = "1icwh684ivrhpwr3xlk861h8hydj7wrap5m7qd7rzqnndlmajrmv";
  };

  goDeps = ./deps.json;

  patches = [
    ./gogs_addOrgMembership.patch
    ./gogs_adminAccessAll.patch
    ./gogs_fixDuplicateIssue.patch
    ./gogs_maxRepoCreationAPI.patch
    ./gogs_teamDefaultAccess.patch
    ./gogs_useBinSH.patch
    ./gogs_addCollaborator.patch
  ];

  propagatedBuildInputs = [
    go-gogs-client
  ];
}
