# This file was generated by go2nix.
{ stdenv, lib, goPackages, cyrus_sasl, fetchFromGitHub, fetchgit, fetchbzr }:

let
  goPkgs = rec {
    "github.com/BurntSushi/toml" = goPackages.buildGoPackage rec {
      name = "BurntSushi-toml";
      goPackagePath = "github.com/BurntSushi/toml";
      src = fetchFromGitHub {
        owner = "BurntSushi";
        repo = "toml";
        rev = "75869ce70f3cd0f6d1473c58f4adac5941f1055a";
        sha256 = "0ckp2hylcf0yg3vmq20gvg3hrpjyca218hi7npv0ghhjva1af8fn";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/Pallinder/go-randomdata" = goPackages.buildGoPackage rec {
      name = "Pallinder-go-randomdata";
      goPackagePath = "github.com/Pallinder/go-randomdata";
      src = fetchFromGitHub {
        owner = "Pallinder";
        repo = "go-randomdata";
        rev = "4134a721d6473f81816b1799866bf3e553a9b8d4";
        sha256 = "1ql4vxvgw7g0cznf2qa8bz449q83n4kwl10n2ln06gkzqfzw3h0a";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/Unknwon/cae" = goPackages.buildGoPackage rec {
      name = "Unknwon-cae";
      goPackagePath = "github.com/Unknwon/cae";
      src = fetchFromGitHub {
        owner = "Unknwon";
        repo = "cae";
        rev = "7f5e046bc8a6c3cde743c233b96ee4fd84ee6ecd";
        sha256 = "1lc7v93d72g1rf8dyk8kw4m15q603mgh7ifz26si4k0csxwzkvdr";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/Unknwon/com"
        goPkgs."github.com/smartystreets/goconvey"
      ];
    };
    "github.com/Unknwon/com" = goPackages.buildGoPackage rec {
      name = "Unknwon-com";
      goPackagePath = "github.com/Unknwon/com";
      src = fetchFromGitHub {
        owner = "Unknwon";
        repo = "com";
        rev = "28b053d5a2923b87ce8c5a08f3af779894a72758";
        sha256 = "09i9slj4zbsqmwkkx9bqi7cgpv6hqby6r98l6qx1wag89qijybz2";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/smartystreets/goconvey"
      ];
    };
    "github.com/Unknwon/i18n" = goPackages.buildGoPackage rec {
      name = "Unknwon-i18n";
      goPackagePath = "github.com/Unknwon/i18n";
      src = fetchFromGitHub {
        owner = "Unknwon";
        repo = "i18n";
        rev = "3b48b6662051bed72d36efa3c1e897bdf96b2e37";
        sha256 = "1922gsa4fhc474jvqvsk66k8r783xx61i1zy6vwrgwdg7jrpdihk";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/Unknwon/com"
        goPkgs."gopkg.in/ini.v0"
        goPkgs."gopkg.in/ini.v1"
      ];
    };
    "github.com/Unknwon/paginater" = goPackages.buildGoPackage rec {
      name = "Unknwon-paginater";
      goPackagePath = "github.com/Unknwon/paginater";
      src = fetchFromGitHub {
        owner = "Unknwon";
        repo = "paginater";
        rev = "7748a72e01415173a27d79866b984328e7b0c12b";
        sha256 = "0ighsa75ixgx6c4hc397c06lapf0pz50cj3cgkdvssp9an38kw2c";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/smartystreets/goconvey"
      ];
    };
    "github.com/alicebob/miniredis" = goPackages.buildGoPackage rec {
      name = "alicebob-miniredis";
      goPackagePath = "github.com/alicebob/miniredis";
      src = fetchFromGitHub {
        owner = "alicebob";
        repo = "miniredis";
        rev = "914ffc3c3cd781fadbdd7dcc003239b108464126";
        sha256 = "168v51cc75bcsck5drngih853wga273m1gnabh7qpp67psvib23i";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/bsm/redeo"
        goPkgs."github.com/garyburd/redigo"
      ];
    };
    "github.com/boltdb/bolt" = goPackages.buildGoPackage rec {
      name = "boltdb-bolt";
      goPackagePath = "github.com/boltdb/bolt";
      src = fetchFromGitHub {
        owner = "boltdb";
        repo = "bolt";
        rev = "b514920f8f2e0a68f857e5a12c774f385a59aef9";
        sha256 = "1s8fk60lngrfyycxpi39j7zp5ig78l8wxjzijk3zj8gi2m08x0w6";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/bradfitz/gomemcache" = goPackages.buildGoPackage rec {
      name = "bradfitz-gomemcache";
      goPackagePath = "github.com/bradfitz/gomemcache";
      src = fetchFromGitHub {
        owner = "bradfitz";
        repo = "gomemcache";
        rev = "fb1f79c6b65acda83063cbc69f6bba1522558bfc";
        sha256 = "0mq5rn07bbpy2yla7hassrmj966p6r7ffbf9w41l31yy0fc07i68";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/bsm/redeo" = goPackages.buildGoPackage rec {
      name = "bsm-redeo";
      goPackagePath = "github.com/bsm/redeo";
      src = fetchFromGitHub {
        owner = "bsm";
        repo = "redeo";
        rev = "436f4440f2ee191b0bfbdf9d12894fe0f1eedd9b";
        sha256 = "03x7v01qwxvq7ggb2xlyjb88vmnwq27vv9qbrs12v1i6xh8x8b6k";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/onsi/ginkgo"
        goPkgs."github.com/onsi/gomega"
      ];
    };
    "github.com/codegangsta/cli" = goPackages.buildGoPackage rec {
      name = "codegangsta-cli";
      goPackagePath = "github.com/codegangsta/cli";
      src = fetchFromGitHub {
        owner = "codegangsta";
        repo = "cli";
        rev = "a2943485b110df8842045ae0600047f88a3a56a1";
        sha256 = "1hdbr6riv7j4all09w2a5zdc27fq11rf005v7v3wdccq07zmsmaa";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/couchbase/cbauth" = goPackages.buildGoPackage rec {
      name = "couchbase-cbauth";
      goPackagePath = "github.com/couchbase/cbauth";
      src = fetchFromGitHub {
        owner = "couchbase";
        repo = "cbauth";
        rev = "5af55adc1fb363179dfd1cafad557b44cefc1294";
        sha256 = "11nqadnbj9qhc803k57qd8l4dv5v6pp2nifkhcmpxvniagx476b1";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/couchbase/go-couchbase"
        goPkgs."github.com/couchbase/gomemcached"
        goPkgs."github.com/couchbase/goutils"
      ];
    };
    "github.com/couchbase/go-couchbase" = goPackages.buildGoPackage rec {
      name = "couchbase-go-couchbase";
      goPackagePath = "github.com/couchbase/go-couchbase";
      goPackageAliases = [
        "github.com/couchbaselabs/go-couchbase"
      ];
      subPackages = [
        "./"
      ];
      src = fetchFromGitHub {
        owner = "couchbase";
        repo = "go-couchbase";
        rev = "6274761ede1026a6a0ca67366bbc0e7b0bea44ea";
        sha256 = "1kfyrbb6mn34k64varshhasjhb176rc7006j0i382f46n3dfyhdm";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/Pallinder/go-randomdata"
        #goPkgs."github.com/couchbase/cbauth"
        goPkgs."github.com/couchbase/gomemcached"
        goPkgs."github.com/couchbase/goutils"
        #goPkgs."github.com/couchbaselabs/go_n1ql"
      ];
    };
    "github.com/couchbase/go_n1ql" = goPackages.buildGoPackage rec {
      name = "couchbase-go_n1ql";
      goPackagePath = "github.com/couchbase/go_n1ql";
      goPackageAliases = [
        "github.com/couchbaselabs/go_n1ql"
      ];
      src = fetchFromGitHub {
        owner = "couchbase";
        repo = "go_n1ql";
        rev = "6cf4e348b127e21f56e53eb8c3faaea56afdc588";
        sha256 = "0nnjpr8mh2j7dbhl871y42gc81n1v5fkv2bl8mmca27hywgh25d4";
      };
      propagatedBuildInputs = [
        #goPkgs."github.com/couchbase/go-couchbase"
        goPkgs."github.com/couchbase/gomemcached"
        goPkgs."github.com/couchbase/goutils"
      ];
    };
    "github.com/couchbase/gomemcached" = goPackages.buildGoPackage rec {
      name = "couchbase-gomemcached";
      goPackagePath = "github.com/couchbase/gomemcached";
      src = fetchFromGitHub {
        owner = "couchbase";
        repo = "gomemcached";
        rev = "a5ea6356f648fec6ab89add00edd09151455b4b2";
        sha256 = "00x57qqdv9ciyxiw2y6p4s65sfgi4cs6zi39qlqlw90nh133xnwi";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/couchbase/goutils"
      ];
    };
    "github.com/couchbase/goutils" = goPackages.buildGoPackage rec {
      name = "couchbase-goutils";
      goPackagePath = "github.com/couchbase/goutils";
      src = fetchFromGitHub {
        owner = "couchbase";
        repo = "goutils";
        rev = "8196588ec83a4cbf049a19473d70906c60ac3a38";
        sha256 = "1f0cq2nnrqdqvfz6ljn9gjq4gb38nwd5h4xvkwv7cn2n4x2pxix8";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/cupcake/rdb" = goPackages.buildGoPackage rec {
      name = "cupcake-rdb";
      goPackagePath = "github.com/cupcake/rdb";
      src = fetchFromGitHub {
        owner = "cupcake";
        repo = "rdb";
        rev = "90399abcaaff31d7844fbae7f9acb27109946f7f";
        sha256 = "1zk5060mvljxds6nrgr10knij6y50l0x322adwvh0vvcdl7iwiyk";
      };
      propagatedBuildInputs = [
        goPkgs."launchpad.net/gocheck"
      ];
    };
    "github.com/davecgh/go-spew" = goPackages.buildGoPackage rec {
      name = "davecgh-go-spew";
      goPackagePath = "github.com/davecgh/go-spew";
      src = fetchFromGitHub {
        owner = "davecgh";
        repo = "go-spew";
        rev = "5215b55f46b2b919f50a1df0eaa5886afe4e3b3d";
        sha256 = "15h9kl73rdbzlfmsdxp13jja5gs7sknvqkpq2qizq3qv3nr1x8dk";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/edsrzf/mmap-go" = goPackages.buildGoPackage rec {
      name = "edsrzf-mmap-go";
      goPackagePath = "github.com/edsrzf/mmap-go";
      src = fetchFromGitHub {
        owner = "edsrzf";
        repo = "mmap-go";
        rev = "903d080718bd2877583fe1bd0a19c9cd3e2906ff";
        sha256 = "0g0phwfk53m346k69qahmddckq4j0i2rmi4xixmbq85p1rjz1m9h";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/garyburd/redigo" = goPackages.buildGoPackage rec {
      name = "garyburd-redigo";
      goPackagePath = "github.com/garyburd/redigo";
      src = fetchFromGitHub {
        owner = "garyburd";
        repo = "redigo";
        rev = "4ed1111375cbeb698249ffe48dd463e9b0a63a7a";
        sha256 = "1j2sn5by9qqgrwnmlz0chl737v1q0y3cwcjw0qq0i38hf2aw5krh";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/go-macaron/binding" = goPackages.buildGoPackage rec {
      name = "go-macaron-binding";
      goPackagePath = "github.com/go-macaron/binding";
      src = fetchFromGitHub {
        owner = "go-macaron";
        repo = "binding";
        rev = "a68f34212fe257219981e43adfe4c96ab48f42cd";
        sha256 = "00ny0khwbcv9n7kbnc2mfl07sp6dyp4xc5y4wiqvsgj66gb90yf7";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/Unknwon/com"
        goPkgs."github.com/go-macaron/inject"
        goPkgs."github.com/smartystreets/goconvey"
        goPkgs."gopkg.in/ini.v1"
        goPkgs."gopkg.in/macaron.v1"
      ];
    };
    "github.com/go-macaron/cache" = goPackages.buildGoPackage rec {
      name = "go-macaron-cache";
      goPackagePath = "github.com/go-macaron/cache";
      src = fetchFromGitHub {
        owner = "go-macaron";
        repo = "cache";
        rev = "56173531277692bc2925924d51fda1cd0a6b8178";
        sha256 = "1116a22wm43q2l54nnycgli90kix787j20mpgya9qb6xnglcck59";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/Unknwon/com"
        goPkgs."github.com/bradfitz/gomemcache"
        goPkgs."github.com/go-macaron/inject"
        goPkgs."github.com/go-sql-driver/mysql"
        goPkgs."github.com/lib/pq"
        goPkgs."github.com/lunny/nodb"
        goPkgs."github.com/siddontang/ledisdb"
        goPkgs."github.com/smartystreets/goconvey"
        goPkgs."gopkg.in/bufio.v1"
        goPkgs."gopkg.in/ini.v1"
        goPkgs."gopkg.in/macaron.v1"
        goPkgs."gopkg.in/redis.v2"
      ];
    };
    "github.com/go-macaron/captcha" = goPackages.buildGoPackage rec {
      name = "go-macaron-captcha";
      goPackagePath = "github.com/go-macaron/captcha";
      src = fetchFromGitHub {
        owner = "go-macaron";
        repo = "captcha";
        rev = "8aa5919789ab301e865595eb4b1114d6b9847deb";
        sha256 = "0wdihxbl7yw4wg2x0wb09kv9swfpr5j06wsj4hxn3xcbpqi9viwm";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/Unknwon/com"
        goPkgs."github.com/go-macaron/cache"
        goPkgs."github.com/go-macaron/inject"
        goPkgs."github.com/smartystreets/goconvey"
        goPkgs."gopkg.in/ini.v1"
        goPkgs."gopkg.in/macaron.v1"
      ];
    };
    "github.com/go-macaron/csrf" = goPackages.buildGoPackage rec {
      name = "go-macaron-csrf";
      goPackagePath = "github.com/go-macaron/csrf";
      src = fetchFromGitHub {
        owner = "go-macaron";
        repo = "csrf";
        rev = "546646cf80d2feabea4e4098d2d824d5582f3416";
        sha256 = "0l2ljqcq1nz569l8cajbsxgyvyrwgg5s69bqqqzf6zl19mdc1g9s";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/Unknwon/com"
        goPkgs."github.com/go-macaron/inject"
        goPkgs."github.com/go-macaron/session"
        goPkgs."github.com/smartystreets/goconvey"
        goPkgs."gopkg.in/ini.v1"
        goPkgs."gopkg.in/macaron.v1"
      ];
    };
    "github.com/go-macaron/gzip" = goPackages.buildGoPackage rec {
      name = "go-macaron-gzip";
      goPackagePath = "github.com/go-macaron/gzip";
      src = fetchFromGitHub {
        owner = "go-macaron";
        repo = "gzip";
        rev = "cad1c6580a07c56f5f6bc52d66002a05985c5854";
        sha256 = "12mq3dd1vd0jbi80fxab4ysmipbz9zhbm9nw6y6a6bw3byc8w4jf";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/Unknwon/com"
        goPkgs."github.com/go-macaron/inject"
        goPkgs."github.com/klauspost/compress"
        goPkgs."github.com/klauspost/cpuid"
        goPkgs."github.com/klauspost/crc32"
        goPkgs."github.com/smartystreets/goconvey"
        goPkgs."gopkg.in/ini.v1"
        goPkgs."gopkg.in/macaron.v1"
      ];
    };
    "github.com/go-macaron/i18n" = goPackages.buildGoPackage rec {
      name = "go-macaron-i18n";
      goPackagePath = "github.com/go-macaron/i18n";
      src = fetchFromGitHub {
        owner = "go-macaron";
        repo = "i18n";
        rev = "d2d3329f13b52314f3292c4cecb601fad13f02c8";
        sha256 = "18f59fkw3wy5b80x8jcqnywqscs7qvj7cnfi85d23m9kq353pifs";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/Unknwon/com"
        goPkgs."github.com/Unknwon/i18n"
        goPkgs."github.com/go-macaron/inject"
        goPkgs."github.com/smartystreets/goconvey"
        goPkgs."gopkg.in/ini.v1"
        goPkgs."gopkg.in/macaron.v1"
      ];
    };
    "github.com/go-macaron/inject" = goPackages.buildGoPackage rec {
      name = "go-macaron-inject";
      goPackagePath = "github.com/go-macaron/inject";
      src = fetchFromGitHub {
        owner = "go-macaron";
        repo = "inject";
        rev = "c5ab7bf3a307593cd44cb272d1a5beea473dd072";
        sha256 = "0v7plrgwx9qn9iknm7p5fr5c53zzx5aaqvdcgyh6hnfwjjf5zny4";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/smartystreets/goconvey"
      ];
    };
    "github.com/go-macaron/session" = goPackages.buildGoPackage rec {
      name = "go-macaron-session";
      goPackagePath = "github.com/go-macaron/session";
      src = fetchFromGitHub {
        owner = "go-macaron";
        repo = "session";
        rev = "66031fcb37a0fff002a1f028eb0b3a815c78306b";
        sha256 = "1prrfv8xdlyxrdbagbqzjkx69x74hjzif5ki4lzl2y6fk3nb0cd5";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/BurntSushi/toml"
        goPkgs."github.com/Unknwon/com"
        goPkgs."github.com/boltdb/bolt"
        goPkgs."github.com/bradfitz/gomemcache"
        goPkgs."github.com/couchbase/go-couchbase"
        goPkgs."github.com/cupcake/rdb"
        goPkgs."github.com/edsrzf/mmap-go"
        goPkgs."github.com/go-macaron/inject"
        goPkgs."github.com/go-sql-driver/mysql"
        goPkgs."github.com/golang/snappy"
        goPkgs."github.com/lib/pq"
        goPkgs."github.com/lunny/log"
        goPkgs."github.com/lunny/nodb"
        goPkgs."github.com/siddontang/go"
        goPkgs."github.com/siddontang/go-snappy"
        goPkgs."github.com/siddontang/ledisdb"
        goPkgs."github.com/siddontang/rdb"
        goPkgs."github.com/smartystreets/goconvey"
        goPkgs."github.com/syndtr/goleveldb"
        goPkgs."gopkg.in/bufio.v1"
        goPkgs."gopkg.in/ini.v1"
        goPkgs."gopkg.in/macaron.v1"
        goPkgs."gopkg.in/redis.v2"
      ];
    };
    "github.com/go-macaron/toolbox" = goPackages.buildGoPackage rec {
      name = "go-macaron-toolbox";
      goPackagePath = "github.com/go-macaron/toolbox";
      src = fetchFromGitHub {
        owner = "go-macaron";
        repo = "toolbox";
        rev = "82b511550b0aefc36b3a28062ad3a52e812bee38";
        sha256 = "0naw8bib332l3k7gwlqz9cqjbryj6f9xvyb8mx6v13pvxds12nsp";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/Unknwon/com"
        goPkgs."github.com/go-macaron/inject"
        goPkgs."github.com/smartystreets/goconvey"
        goPkgs."gopkg.in/ini.v1"
        goPkgs."gopkg.in/macaron.v1"
      ];
    };
    "github.com/go-sql-driver/mysql" = goPackages.buildGoPackage rec {
      name = "go-sql-driver-mysql";
      goPackagePath = "github.com/go-sql-driver/mysql";
      src = fetchFromGitHub {
        owner = "go-sql-driver";
        repo = "mysql";
        rev = "0f2db9e6c9cff80a97ca5c2c5096242cc1554e16";
        sha256 = "0pwn9aix0xnsvcrzm902sfnq0kf2f0kh4s6vknzzak73mdqyvx4k";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/go-xorm/core" = goPackages.buildGoPackage rec {
      name = "go-xorm-core";
      goPackagePath = "github.com/go-xorm/core";
      src = fetchFromGitHub {
        owner = "go-xorm";
        repo = "core";
        rev = "502158401cde814951eae62f064d9e5ff39e13ce";
        sha256 = "1kw9grlag2dgr3k4mr6vx804r914pybgwzhwr8h6jrg2ixmq5d69";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/go-sql-driver/mysql"
        goPkgs."github.com/mattn/go-sqlite3"
      ];
    };
    "github.com/go-xorm/xorm" = goPackages.buildGoPackage rec {
      name = "go-xorm-xorm";
      goPackagePath = "github.com/go-xorm/xorm";
      src = fetchFromGitHub {
        owner = "go-xorm";
        repo = "xorm";
        rev = "1045aa020f6ad8a445bdb748d088bccc1fdc58f1";
        sha256 = "19wljn3wi1bcwmzr19adn784yiwh4dbjns4jy9c3f1n56xz1siz9";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/go-sql-driver/mysql"
        goPkgs."github.com/go-xorm/core"
        goPkgs."github.com/lib/pq"
        goPkgs."github.com/mattn/go-sqlite3"
      ];
    };
    "github.com/gogits/chardet" = goPackages.buildGoPackage rec {
      name = "gogits-chardet";
      goPackagePath = "github.com/gogits/chardet";
      src = fetchFromGitHub {
        owner = "gogits";
        repo = "chardet";
        rev = "2404f777256163ea3eadb273dada5dcb037993c0";
        sha256 = "1dki2pqhnzcmzlqrq4d4jwknnjxm82xqnmizjjdblb6h98ans1cd";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/saintfish/chardet"
      ];
    };
    "github.com/gogits/cron" = goPackages.buildGoPackage rec {
      name = "gogits-cron";
      goPackagePath = "github.com/gogits/cron";
      src = fetchFromGitHub {
        owner = "gogits";
        repo = "cron";
        rev = "3abc0f88f2062336bcc41b43a4febbd847a390ce";
        sha256 = "0kxx090a5gyl3ri0d9sfm9x3hg5w5j5bnqvynshnqjz5wqcrhpcr";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/gogits/git-module" = goPackages.buildGoPackage rec {
      name = "gogits-git-module";
      goPackagePath = "github.com/gogits/git-module";
      src = fetchFromGitHub {
        owner = "gogits";
        repo = "git-module";
        rev = "76e8cce6c7ef3ba1cf75752261c721ebf14cd129";
        sha256 = "0b3dpzhl1wdcfcv8xwpwxg9prlid8yjxxadp5xh2qpbm4x49bn8z";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/mcuadros/go-version"
        goPkgs."github.com/smartystreets/goconvey"
      ];
    };
    "github.com/gogits/go-gogs-client" = goPackages.buildGoPackage rec {
      name = "gogits-go-gogs-client";
      goPackagePath = "github.com/gogits/go-gogs-client";
      src = fetchFromGitHub {
        owner = "gogits";
        repo = "go-gogs-client";
        rev = "d584b1e0fb4d8ad0e8cf2fae2368838f2526b408";
        sha256 = "0vrxil4vp682s2fn3fj2kmiv34f0ib8a3y62g1qfr7nhhbhqi4c5";
      };
      patches = [
        ./go-gogs-client_addCollaborator.patch
        ./go-gogs-client_addOrgMembership.patch
        ./go-gogs-client_maxRepoCreationAPI.patch
      ];
      propagatedBuildInputs = [
      ];
    };
    "github.com/gogits/gogs" = goPackages.buildGoPackage rec {
      name = "gogits-gogs-${version}";
      version = "0.9.0";
      goPackagePath = "github.com/gogits/gogs";
      src = fetchFromGitHub {
        owner = "gogits";
        repo = "gogs";
        rev = "0ea0c5ec4f24f0fc5ef3231085c74b33a16f98ec";
        sha256 = "1739gpk6nc3flz3w89g55q2jck3l27n7bfpr888hdnhc8r13j736";
      };
      patches = [
        ./gogs_addOrgMembership.patch
        ./gogs_addCollaborator.patch
        ./gogs_maxRepoCreationAPI.patch
        ./gogs_useBinSH.patch
      ];
      propagatedBuildInputs = [
        goPkgs."github.com/Unknwon/cae"
        goPkgs."github.com/Unknwon/com"
        goPkgs."github.com/Unknwon/i18n"
        goPkgs."github.com/Unknwon/paginater"
        goPkgs."github.com/bradfitz/gomemcache"
        goPkgs."github.com/codegangsta/cli"
        goPkgs."github.com/go-macaron/binding"
        goPkgs."github.com/go-macaron/cache"
        goPkgs."github.com/go-macaron/captcha"
        goPkgs."github.com/go-macaron/csrf"
        goPkgs."github.com/go-macaron/gzip"
        goPkgs."github.com/go-macaron/i18n"
        goPkgs."github.com/go-macaron/inject"
        goPkgs."github.com/go-macaron/session"
        goPkgs."github.com/go-macaron/toolbox"
        goPkgs."github.com/go-sql-driver/mysql"
        goPkgs."github.com/go-xorm/core"
        goPkgs."github.com/go-xorm/xorm"
        goPkgs."github.com/gogits/chardet"
        goPkgs."github.com/gogits/cron"
        goPkgs."github.com/gogits/git-module"
        goPkgs."github.com/gogits/go-gogs-client"
        goPkgs."github.com/issue9/identicon"
        goPkgs."github.com/klauspost/compress"
        goPkgs."github.com/klauspost/cpuid"
        goPkgs."github.com/klauspost/crc32"
        goPkgs."github.com/lib/pq"
        goPkgs."github.com/mcuadros/go-version"
        goPkgs."github.com/microcosm-cc/bluemonday"
        goPkgs."github.com/nfnt/resize"
        goPkgs."github.com/russross/blackfriday"
        goPkgs."github.com/satori/go.uuid"
        goPkgs."github.com/sergi/go-diff"
        goPkgs."github.com/shurcooL/sanitized_anchor_name"
        goPkgs."github.com/smartystreets/goconvey"
        goPkgs."golang.org/x/crypto"
        goPkgs."golang.org/x/net"
        goPkgs."golang.org/x/text"
        goPkgs."gopkg.in/asn1-ber.v1"
        goPkgs."gopkg.in/bufio.v1"
        goPkgs."gopkg.in/gomail.v2"
        goPkgs."gopkg.in/ini.v1"
        goPkgs."gopkg.in/ldap.v2"
        goPkgs."gopkg.in/macaron.v1"
        goPkgs."gopkg.in/redis.v2"
      ];
    };
    "github.com/golang/protobuf" = goPackages.buildGoPackage rec {
      name = "golang-protobuf";
      goPackagePath = "github.com/golang/protobuf";
      src = fetchFromGitHub {
        owner = "golang";
        repo = "protobuf";
        rev = "c75fbf01dc6cb73649c4cd4326182c3e44aa9dbb";
        sha256 = "08g8mn4qf8hb43hha1m2nrxn5bs1x85vc0wdspz5sq88w08m2ypj";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/golang/snappy" = goPackages.buildGoPackage rec {
      name = "golang-snappy";
      goPackagePath = "github.com/golang/snappy";
      src = fetchFromGitHub {
        owner = "golang";
        repo = "snappy";
        rev = "5f1c01d9f64b941dd9582c638279d046eda6ca31";
        sha256 = "0qyhbgdjy2gf93y9c1n54a6ql75vinvwdqn6i4fi8i773j0vdjvf";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/gorilla/websocket" = goPackages.buildGoPackage rec {
      name = "gorilla-websocket";
      goPackagePath = "github.com/gorilla/websocket";
      src = fetchFromGitHub {
        owner = "gorilla";
        repo = "websocket";
        rev = "c45a635370221f34fea2d5163fd156fcb4e38e8a";
        sha256 = "0vsgdsms962scdd7vpjiiv6fbxjk4w4bjnnjj7ixna9z2klq19kv";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/issue9/assert" = goPackages.buildGoPackage rec {
      name = "issue9-assert";
      goPackagePath = "github.com/issue9/assert";
      src = fetchFromGitHub {
        owner = "issue9";
        repo = "assert";
        rev = "26d40b5ae061a783b6f7cebec05658d24ab851b9";
        sha256 = "0rxs8v8m1ay0aan7cawkasd16w2iqrild03n4gcr6ayiy9k8cycf";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/issue9/identicon" = goPackages.buildGoPackage rec {
      name = "issue9-identicon";
      goPackagePath = "github.com/issue9/identicon";
      src = fetchFromGitHub {
        owner = "issue9";
        repo = "identicon";
        rev = "f8c0d2ce04db79c663b1da33d3a9f62be753ee88";
        sha256 = "0x9yk9lryapfwjbip3cdpxsjnpsjvqdnciz63jnl1igw85srg06s";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/issue9/assert"
      ];
    };
    "github.com/jtolds/gls" = goPackages.buildGoPackage rec {
      name = "jtolds-gls";
      goPackagePath = "github.com/jtolds/gls";
      src = fetchFromGitHub {
        owner = "jtolds";
        repo = "gls";
        rev = "8ddce2a84170772b95dd5d576c48d517b22cac63";
        sha256 = "11rp9wbzkd71640rq0nwmgsddskx3qac8wzqz71ksdb7ixjj5fmj";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/klauspost/compress" = goPackages.buildGoPackage rec {
      name = "klauspost-compress";
      goPackagePath = "github.com/klauspost/compress";
      src = fetchFromGitHub {
        owner = "klauspost";
        repo = "compress";
        rev = "2d3d403f37d2e70b722590bc286076a17422e1f2";
        sha256 = "0d8wh7dc3v804n1bxyjxaa330sdzibqa4913grbdz7ax51mqy4zw";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/golang/snappy"
        goPkgs."github.com/klauspost/cpuid"
        goPkgs."github.com/klauspost/crc32"
      ];
    };
    "github.com/klauspost/cpuid" = goPackages.buildGoPackage rec {
      name = "klauspost-cpuid";
      goPackagePath = "github.com/klauspost/cpuid";
      src = fetchFromGitHub {
        owner = "klauspost";
        repo = "cpuid";
        rev = "09cded8978dc9e80714c4d85b0322337b0a1e5e0";
        sha256 = "05l8pfch0gvxh0khapwxhsk4xajn40vbjr360n49vh2z5531v2xq";
      };
      propagatedBuildInputs = [
        goPackages.net
      ];
    };
    "github.com/klauspost/crc32" = goPackages.buildGoPackage rec {
      name = "klauspost-crc32";
      goPackagePath = "github.com/klauspost/crc32";
      src = fetchFromGitHub {
        owner = "klauspost";
        repo = "crc32";
        rev = "19b0b332c9e4516a6370a0456e6182c3b5036720";
        sha256 = "0fcnsf1m0bzplgp28dz8skza6l7rc65s180x85rzbdl9l3zzi43r";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/lib/pq" = goPackages.buildGoPackage rec {
      name = "lib-pq";
      goPackagePath = "github.com/lib/pq";
      src = fetchFromGitHub {
        owner = "lib";
        repo = "pq";
        rev = "165a3529e799da61ab10faed1fabff3662d6193f";
        sha256 = "1pkrav0sfd1hbq1vmpba4dm7i1r8hik6lsbg5mk2w004gg8nljqs";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/lunny/log" = goPackages.buildGoPackage rec {
      name = "lunny-log";
      goPackagePath = "github.com/lunny/log";
      src = fetchFromGitHub {
        owner = "lunny";
        repo = "log";
        rev = "db601cfd560df77dc022766a622be6cdc28da3bf";
        sha256 = "0nxgw6ckpbzw3ircyvrnc43x7cklk553kzmbs4q6zfcjpv4lcy4h";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/mattn/go-sqlite3"
      ];
    };
    "github.com/lunny/nodb" = goPackages.buildGoPackage rec {
      name = "lunny-nodb";
      goPackagePath = "github.com/lunny/nodb";
      src = fetchFromGitHub {
        owner = "lunny";
        repo = "nodb";
        rev = "5a984cd121ee9cab603471106c215a73edcb5295";
        sha256 = "00m1in18fz3drhx5ribjjdrlh4219mbzyx7y3r8khlasiq3xjxmm";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/BurntSushi/toml"
        goPkgs."github.com/golang/snappy"
        goPkgs."github.com/lunny/log"
        goPkgs."github.com/siddontang/go-snappy"
        goPkgs."github.com/syndtr/goleveldb"
      ];
    };
    "github.com/mattn/go-sqlite3" = goPackages.buildGoPackage rec {
      name = "mattn-go-sqlite3";
      goPackagePath = "github.com/mattn/go-sqlite3";
      src = fetchFromGitHub {
        owner = "mattn";
        repo = "go-sqlite3";
        rev = "f544db98ccf4918ec2ec090a4d74450ef45b4b1c";
        sha256 = "1mp1z6wzmwwjihwjvbm7qcb18g3yf5silpr62kc3wky27d3lqhdn";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/mcuadros/go-version" = goPackages.buildGoPackage rec {
      name = "mcuadros-go-version";
      goPackagePath = "github.com/mcuadros/go-version";
      src = fetchFromGitHub {
        owner = "mcuadros";
        repo = "go-version";
        rev = "d52711f8d6bea8dc01efafdb68ad95a4e2606630";
        sha256 = "08ps27vvn77jhrnks8p8mx5cwgb1ikhaddcnrpgpz7aq905a5kzn";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/microcosm-cc/bluemonday" = goPackages.buildGoPackage rec {
      name = "microcosm-cc-bluemonday";
      goPackagePath = "github.com/microcosm-cc/bluemonday";
      src = fetchFromGitHub {
        owner = "microcosm-cc";
        repo = "bluemonday";
        rev = "4ac6f27528d0a3f2a59e0b0a6f6b3ff0bb89fe20";
        sha256 = "0a927aimqjhpb47zn4xn4hv201davfkb8x21nckg2zrjzbwngkyw";
      };
      propagatedBuildInputs = [
        goPkgs."golang.org/x/net"
      ];
    };
    "github.com/nfnt/resize" = goPackages.buildGoPackage rec {
      name = "nfnt-resize";
      goPackagePath = "github.com/nfnt/resize";
      src = fetchFromGitHub {
        owner = "nfnt";
        repo = "resize";
        rev = "4d93a29130b1b6aba503e2aa8b50f516213ea80e";
        sha256 = "1s6z241726nd1xd5rwlnj6l4p0na4v20ibfg5sh9cp7pl98mn5gv";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/onsi/ginkgo" = goPackages.buildGoPackage rec {
      name = "onsi-ginkgo";
      goPackagePath = "github.com/onsi/ginkgo";
      src = fetchFromGitHub {
        owner = "onsi";
        repo = "ginkgo";
        rev = "ac3d45ddd7ef5c4d7fc4d037b615a81f4d67981e";
        sha256 = "1kq82l8x1ky03hcv8zdllvzqddf8i1yxajj76w21cchd1akzqr78";
      };
      #propagatedBuildInputs = [
      #  goPkgs."github.com/onsi/gomega"
      #];
    };
    "github.com/onsi/gomega" = goPackages.buildGoPackage rec {
      name = "onsi-gomega";
      goPackagePath = "github.com/onsi/gomega";
      src = fetchFromGitHub {
        owner = "onsi";
        repo = "gomega";
        rev = "7ce781ea776b2fd506491011353bded2e40c8467";
        sha256 = "01876g5h9mj8dv07pl4c16ymffdvkkc8jw5qp2j0i40bm95zgnl3";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/golang/protobuf"
        #goPkgs."github.com/onsi/ginkgo"
      ];
    };
    "github.com/peterh/liner" = goPackages.buildGoPackage rec {
      name = "peterh-liner";
      goPackagePath = "github.com/peterh/liner";
      src = fetchFromGitHub {
        owner = "peterh";
        repo = "liner";
        rev = "ad1edfd30321d8f006ccf05f1e0524adeb943060";
        sha256 = "0c24d9j1gnq7r982h1l2isp3d37379qw155hr8ihx9i2mhpfz317";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/pmezard/go-difflib" = goPackages.buildGoPackage rec {
      name = "pmezard-go-difflib";
      goPackagePath = "github.com/pmezard/go-difflib";
      src = fetchFromGitHub {
        owner = "pmezard";
        repo = "go-difflib";
        rev = "792786c7400a136282c1664665ae0a8db921c6c2";
        sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/russross/blackfriday" = goPackages.buildGoPackage rec {
      name = "russross-blackfriday";
      goPackagePath = "github.com/russross/blackfriday";
      src = fetchFromGitHub {
        owner = "russross";
        repo = "blackfriday";
        rev = "006144af03eeeff1037240a71865a9fd61f1c25f";
        sha256 = "04r9jz996cv5hfib4hnqs6zlva6c6ic05hk89an8fiiic0ky5a53";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/shurcooL/sanitized_anchor_name"
      ];
    };
    "github.com/saintfish/chardet" = goPackages.buildGoPackage rec {
      name = "saintfish-chardet";
      goPackagePath = "github.com/saintfish/chardet";
      src = fetchFromGitHub {
        owner = "saintfish";
        repo = "chardet";
        rev = "3af4cd4741ca4f3eb0c407c034571a6fb0ea529c";
        sha256 = "0czh50md64k9lbllayq0asir3174saxb88yzxrh640yhfxd98pcb";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/satori/go.uuid" = goPackages.buildGoPackage rec {
      name = "satori-go.uuid";
      goPackagePath = "github.com/satori/go.uuid";
      src = fetchFromGitHub {
        owner = "satori";
        repo = "go.uuid";
        rev = "e673fdd4dea8a7334adbbe7f57b7e4b00bdc5502";
        sha256 = "0nm2dqj87vvv1bmcfl3x9k6kal655yfamxnb7xkfzqkvldigy0qf";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/sergi/go-diff" = goPackages.buildGoPackage rec {
      name = "sergi-go-diff";
      goPackagePath = "github.com/sergi/go-diff";
      src = fetchFromGitHub {
        owner = "sergi";
        repo = "go-diff";
        rev = "ec7fdbb58eb3e300c8595ad5ac74a5aa50019cc7";
        sha256 = "1lpxhwqbypssj2vhlkj11fircllvxx4n985w6f76id5jany05h2w";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/stretchr/testify"
      ];
    };
    "github.com/shurcooL/sanitized_anchor_name" = goPackages.buildGoPackage rec {
      name = "shurcooL-sanitized_anchor_name";
      goPackagePath = "github.com/shurcooL/sanitized_anchor_name";
      src = fetchFromGitHub {
        owner = "shurcooL";
        repo = "sanitized_anchor_name";
        rev = "10ef21a441db47d8b13ebcc5fd2310f636973c77";
        sha256 = "1cnbzcf47cn796rcjpph1s64qrabhkv5dn9sbynsy7m9zdwr5f01";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/siddontang/go" = goPackages.buildGoPackage rec {
      name = "siddontang-go";
      goPackagePath = "github.com/siddontang/go";
      src = fetchFromGitHub {
        owner = "siddontang";
        repo = "go";
        rev = "354e14e6c093c661abb29fd28403b3c19cff5514";
        sha256 = "0pfha6av8qw4fxf21n64m6pw6bri254g7gwh5rvnd0qipdgkn131";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/gorilla/websocket"
        goPkgs."gopkg.in/check.v1"
        goPkgs."gopkg.in/mgo.v2"
      ];
    };
    "github.com/siddontang/go-snappy" = goPackages.buildGoPackage rec {
      name = "siddontang-go-snappy";
      goPackagePath = "github.com/siddontang/go-snappy";
      src = fetchFromGitHub {
        owner = "siddontang";
        repo = "go-snappy";
        rev = "d8f7bb82a96d89c1254e5a6c967134e1433c9ee2";
        sha256 = "11h25k4h8mdnhm8jyllsvv597bgbq3zf5ym2ccppla1jflp5r3jg";
      };
      propagatedBuildInputs = [
      ];
    };
    "github.com/siddontang/goredis" = goPackages.buildGoPackage rec {
      name = "siddontang-goredis";
      goPackagePath = "github.com/siddontang/goredis";
      src = fetchFromGitHub {
        owner = "siddontang";
        repo = "goredis";
        rev = "760763f78400635ed7b9b115511b8ed06035e908";
        sha256 = "1x5zh61c0zcbc111w6bsa73njfrg5fphpql9rccy8kfvyfv7ahxq";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/alicebob/miniredis"
      ];
    };
    "github.com/siddontang/ledisdb" = goPackages.buildGoPackage rec {
      name = "siddontang-ledisdb";
      goPackagePath = "github.com/siddontang/ledisdb";
      src = fetchFromGitHub {
        owner = "siddontang";
        repo = "ledisdb";
        rev = "713b22910a0b66d098c9e40ff19be258968e9a7d";
        sha256 = "0rvv4p66n2mgfg58lbygf1207cnbhls55fxjmkpg6npvl5kwm0b1";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/BurntSushi/toml"
        goPkgs."github.com/boltdb/bolt"
        goPkgs."github.com/edsrzf/mmap-go"
        goPkgs."github.com/golang/snappy"
        goPkgs."github.com/peterh/liner"
        goPkgs."github.com/siddontang/go"
        goPkgs."github.com/siddontang/goredis"
        goPkgs."github.com/siddontang/rdb"
        goPkgs."github.com/syndtr/goleveldb"
        goPkgs."github.com/ugorji/go"
      ];
    };
    "github.com/siddontang/rdb" = goPackages.buildGoPackage rec {
      name = "siddontang-rdb";
      goPackagePath = "github.com/siddontang/rdb";
      src = fetchFromGitHub {
        owner = "siddontang";
        repo = "rdb";
        rev = "fc89ed2e418d27e3ea76e708e54276d2b44ae9cf";
        sha256 = "107wb2kcg67iggfx1bjmm5nhy8cg96zi1iw7nkv9dydivnvalbbd";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/cupcake/rdb"
      ];
    };
    "github.com/smartystreets/assertions" = goPackages.buildGoPackage rec {
      name = "smartystreets-assertions";
      goPackagePath = "github.com/smartystreets/assertions";
      subPackages = [
        "./."
      ];
      src = fetchFromGitHub {
        owner = "smartystreets";
        repo = "assertions";
        rev = "e9a2f6771d97c709b2f7609fdf89ebde8b64c926";
        sha256 = "0vjmihrl9h5npq2w1qgfl3lvfyl314an50rzqrhkwkb3gnks8b16";
      };
      propagatedBuildInputs = [
        goPkgs."golang.org/x/net"
      ];
    };
    "github.com/smartystreets/goconvey" = goPackages.buildGoPackage rec {
      name = "smartystreets-goconvey";
      goPackagePath = "github.com/smartystreets/goconvey";
      src = fetchFromGitHub {
        owner = "smartystreets";
        repo = "goconvey";
        rev = "99f2b1e01343c8bc2d9d12f1194d2d68ce18b063";
        sha256 = "1gp5aycg1phv11fxa9a37jklcr54zaw0d3swz8fxdw2jk0apmxsv";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/jtolds/gls"
        goPkgs."github.com/smartystreets/assertions"
      ];
    };
    "github.com/stretchr/objx" = goPackages.buildGoPackage rec {
      name = "stretchr-objx";
      goPackagePath = "github.com/stretchr/objx";
      src = fetchFromGitHub {
        owner = "stretchr";
        repo = "objx";
        rev = "1a9d0bb9f541897e62256577b352fdbc1fb4fd94";
        sha256 = "1n027ksls1rn1ja98kd0cd2kv1vwlzsl0d7xnh3yqf451vh0md50";
      };
      propagatedBuildInputs = [
        (goPackages.buildGoPackage rec {
          name = "stretchr-objx-assert";
          goPackagePath = "github.com/stretchr/testify";
          goPackageAliases = [
            "github.com/stretchrcom/testify"
          ];
          subPackages = [
            "./assert"
          ];
          src = fetchFromGitHub {
            owner = "stretchr";
            repo = "testify";
            rev = "1f4a1643a57e798696635ea4c126e9127adb7d3c";
            sha256 = "0nam9d68rn8ha8ldif22kkgv6k6ph3y88fp26159wdrs63ca3bzl";
          };
          propagatedBuildInputs = [
            goPkgs."github.com/davecgh/go-spew"
            goPkgs."github.com/pmezard/go-difflib"
          ];
        })
      ];
    };
    "github.com/stretchr/testify" = goPackages.buildGoPackage rec {
      name = "stretchr-testify";
      goPackagePath = "github.com/stretchr/testify";
      goPackageAliases = [
        "github.com/stretchrcom/testify"
      ];
      src = fetchFromGitHub {
        owner = "stretchr";
        repo = "testify";
        rev = "6fe211e493929a8aac0469b93f28b1d0688a9a3a";
        sha256 = "0pa2niaqikxin63y7bzksjisv700ss3wvc63lpqiy7ccgf6l5gbm";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/davecgh/go-spew"
        goPkgs."github.com/pmezard/go-difflib"
        goPkgs."github.com/stretchr/objx"
      ];
    };
    "github.com/syndtr/goleveldb" = goPackages.buildGoPackage rec {
      name = "syndtr-goleveldb";
      goPackagePath = "github.com/syndtr/goleveldb";
      src = fetchFromGitHub {
        owner = "syndtr";
        repo = "goleveldb";
        rev = "ad0d8b2ab58a55ed5c58073aa46451d5e1ca1280";
        sha256 = "1xw6nk844qq5s0ir710y10liqa8z8m5ynzjmm3ws722rifgwvy0k";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/golang/snappy"
        goPkgs."github.com/onsi/ginkgo"
        goPkgs."github.com/onsi/gomega"
      ];
    };
    "github.com/ugorji/go" = goPackages.buildGoPackage rec {
      name = "ugorji-go";
      goPackagePath = "github.com/ugorji/go";
      src = fetchFromGitHub {
        owner = "ugorji";
        repo = "go";
        rev = "187fa0f8af224437e08ecb3f208c4d1a94859a61";
        sha256 = "000a3vx2c0rsamd3rvv1a4analyfvbbpbm9fi48yj0bgb1m53h3r";
      };
      propagatedBuildInputs = [
      ];
    };
    "golang.org/x/crypto" = goPackages.buildGoPackage rec {
      name = "x-crypto";
      goPackagePath = "golang.org/x/crypto";
      src = fetchgit {
        url = "https://go.googlesource.com/crypto";
        rev = "5dc8cb4b8a8eb076cbb5a06bc3b8682c15bdbbd3";
        sha256 = "0b2s9gidpy2r85z0n9w2knh3dkfhjg89z3lyi620vcf1li6qhdl3";
      };
      propagatedBuildInputs = [
      ];
    };
    "golang.org/x/net" = goPackages.buildGoPackage rec {
      name = "x-net";
      goPackagePath = "golang.org/x/net";
      src = fetchgit {
        url = "https://go.googlesource.com/net";
        rev = "a4bbce9fcae005b22ae5443f6af064d80a6f5a55";
        sha256 = "1c3ms9nhrxibmhd5m3kyrby6aq6f2winiz6cijcy3jrq491msaap";
      };
      propagatedBuildInputs = [
        goPkgs."golang.org/x/crypto"
        goPkgs."golang.org/x/text"
      ];
    };
    "golang.org/x/text" = goPackages.buildGoPackage rec {
      name = "x-text";
      goPackagePath = "golang.org/x/text";
      src = fetchgit {
        url = "https://go.googlesource.com/text";
        rev = "a71fd10341b064c10f4a81ceac72bcf70f26ea34";
        sha256 = "1wm63llpn1ix85f47ac3c9jx92i9cfbdw2ih7p8gdq964k7px53c";
      };
      propagatedBuildInputs = [
      ];
    };
    "gopkg.in/asn1-ber.v1" = goPackages.buildGoPackage rec {
      name = "asn1-ber.v1-";
      goPackagePath = "gopkg.in/asn1-ber.v1";
      src = fetchgit {
        url = "https://gopkg.in/asn1-ber.v1";
        rev = "4e86f4367175e39f69d9358a5f17b4dda270378d";
        sha256 = "13p8s74kzklb5lklfpxwxb78rknihawv1civ4s9bfqx565010fwk";
      };
      propagatedBuildInputs = [
      ];
    };
    "gopkg.in/bufio.v1" = goPackages.buildGoPackage rec {
      name = "bufio.v1-";
      goPackagePath = "gopkg.in/bufio.v1";
      src = fetchgit {
        url = "https://gopkg.in/bufio.v1";
        rev = "567b2bfa514e796916c4747494d6ff5132a1dfce";
        sha256 = "1z5pj778hdianlfj14p0d67g69v4gc2kvn6jg27z5jf75a88l19b";
      };
      propagatedBuildInputs = [
      ];
    };
    "gopkg.in/check.v1" = goPackages.buildGoPackage rec {
      name = "check.v1-";
      goPackagePath = "gopkg.in/check.v1";
      src = fetchgit {
        url = "https://gopkg.in/check.v1";
        rev = "4f90aeace3a26ad7021961c297b22c42160c7b25";
        sha256 = "1mk7wx664abkm3s6qc84l4llxn110kgm4iax9iry8z3718axa08j";
      };
      propagatedBuildInputs = [
      ];
    };
    "gopkg.in/gomail.v2" = goPackages.buildGoPackage rec {
      name = "gomail.v2-";
      goPackagePath = "gopkg.in/gomail.v2";
      src = fetchgit {
        url = "https://gopkg.in/gomail.v2";
        rev = "5ceb8e65415e45e1262fb385212b8193b55c0f99";
        sha256 = "03qqcfi50lp54dvfk5fxxfnwsvas6n2029ikgp1i7nd59jv7i1bm";
      };
      propagatedBuildInputs = [
      ];
    };
    "gopkg.in/ini.v0" = goPackages.buildGoPackage rec {
      name = "ini.v0-";
      goPackagePath = "gopkg.in/ini.v0";
      src = fetchgit {
        url = "https://gopkg.in/ini.v0";
        rev = "70a46eeb84707a1d77984c1a5b7af666063fc5e7";
        sha256 = "1mlzgh2zkzffg1mrwv8pkjl1i8xd9kzim0z57bq2wlxy027yaxyf";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/smartystreets/goconvey"
      ];
    };
    "gopkg.in/ini.v1" = goPackages.buildGoPackage rec {
      name = "ini.v1-";
      goPackagePath = "gopkg.in/ini.v1";
      src = fetchgit {
        url = "https://gopkg.in/ini.v1";
        rev = "776aa739ce9373377cd16f526cdf06cb4c89b40f";
        sha256 = "04pmr4mdvpzawpxinwqpas4ksjzq54q5a0qapw0kkb651p06vqhn";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/smartystreets/goconvey"
      ];
    };
    "gopkg.in/ldap.v2" = goPackages.buildGoPackage rec {
      name = "ldap.v2-";
      goPackagePath = "gopkg.in/ldap.v2";
      src = fetchgit {
        url = "https://gopkg.in/ldap.v2";
        rev = "07a7330929b9ee80495c88a4439657d89c7dbd87";
        sha256 = "0qsy0ldvkd0rhh6wfdrm51145ps9sd8nc8qx3fw1f90irb3a71sh";
      };
      propagatedBuildInputs = [
        goPkgs."gopkg.in/asn1-ber.v1"
      ];
    };
    "gopkg.in/macaron.v1" = goPackages.buildGoPackage rec {
      name = "macaron.v1-";
      goPackagePath = "gopkg.in/macaron.v1";
      src = fetchgit {
        url = "https://gopkg.in/macaron.v1";
        rev = "b9eee382bef2f2f678fadbcf368fc1e52306bed1";
        sha256 = "1rbj1l8742vgar4zchf4r203qvids9vv0iz9a20l5585xz21cmsj";
      };
      propagatedBuildInputs = [
        goPkgs."github.com/Unknwon/com"
        goPkgs."github.com/go-macaron/inject"
        goPkgs."github.com/smartystreets/goconvey"
        goPkgs."gopkg.in/ini.v1"
      ];
    };
    "gopkg.in/mgo.v2" = goPackages.buildGoPackage rec {
      name = "mgo.v2-";
      goPackagePath = "gopkg.in/mgo.v2";
      src = fetchgit {
        url = "https://gopkg.in/mgo.v2";
        rev = "d90005c5262a3463800497ea5a89aed5fe22c886";
        sha256 = "1z81k6mnfk07hkrkw31l16qycyiwa6wzyhysmywgkh58sm5dc9m7";
      };
      propagatedBuildInputs = [
        goPkgs."gopkg.in/check.v1"
        goPkgs."gopkg.in/tomb.v2"
        goPkgs."gopkg.in/yaml.v2"
        cyrus_sasl
      ];
    };
    "gopkg.in/redis.v2" = goPackages.buildGoPackage rec {
      name = "redis.v2-";
      goPackagePath = "gopkg.in/redis.v2";
      src = fetchgit {
        url = "https://gopkg.in/redis.v2";
        rev = "e6179049628164864e6e84e973cfb56335748dea";
        sha256 = "02hifpgak39y39lbn7v2ybbpk3rmb8nvmb3h3490frr8s4pfkb8h";
      };
      propagatedBuildInputs = [
        goPkgs."gopkg.in/bufio.v1"
        goPkgs."gopkg.in/check.v1"
      ];
    };
    "gopkg.in/tomb.v2" = goPackages.buildGoPackage rec {
      name = "tomb.v2-";
      goPackagePath = "gopkg.in/tomb.v2";
      src = fetchgit {
        url = "https://gopkg.in/tomb.v2";
        rev = "14b3d72120e8d10ea6e6b7f87f7175734b1faab8";
        sha256 = "1nza31jvkpka5431c4bdbirvjdy36b1b55sbzljqhqih25jrcjx5";
      };
      propagatedBuildInputs = [
      ];
    };
    "gopkg.in/yaml.v2" = goPackages.buildGoPackage rec {
      name = "yaml.v2-";
      goPackagePath = "gopkg.in/yaml.v2";
      src = fetchgit {
        url = "https://gopkg.in/yaml.v2";
        rev = "a83829b6f1293c91addabc89d0571c246397bbf4";
        sha256 = "1m4dsmk90sbi17571h6pld44zxz7jc4lrnl4f27dpd1l8g5xvjhh";
      };
      propagatedBuildInputs = [
        goPkgs."gopkg.in/check.v1"
      ];
    };
    "launchpad.net/gocheck" = goPackages.buildGoPackage rec {
      name = "gocheck-";
      goPackagePath = "launchpad.net/gocheck";
      src = fetchbzr {
        url = "https://launchpad.net/gocheck";
        rev = "87";
        sha256 = "1y9fa2mv61if51gpik9isls48idsdz87zkm1p3my7swjdix7fcl0";
      };
      propagatedBuildInputs = [
      ];
    };
  };
in
  goPkgs."github.com/gogits/gogs"
